services:
  db:
    container_name: oracle_db_mooc_
    image: gvenzl/oracle-xe:21-slim-faststart
    environment:
      - ORACLE_DATABASE=mooc_db
      - ORACLE_PASSWORD=password
      - APP_USER=mooc_service
      - APP_USER_PASSWORD=password
    ports:
      - "1521:1521"

  redis:
    container_name: redis_mooc
    image: redis:7.2
    ports:
      - "6379:6379"
